"""
Inventário central de automações do hub — fonte única de verdade.

Consumido por: CLI (`automations`), MCP (`listar_automacoes`) e README.
Ao adicionar uma automação nova (CLI, MCP ou script), adicione UMA linha
aqui. `status`:
  ok      — pronta e testada; `run` mostra como executar
  planned — endpoint mapeado (PANEL_MAP.md) mas ainda sem fiação
  blocked — existe no painel; exige aprovação explícita do dono (escrita
            em clientes reais / destrutiva em massa)
"""

AUTOMATIONS = [
    # ---- sigma: sessão e leitura ---------------------------------------------
    {"id": "sigma.login", "site": "sigma", "kind": "auth", "status": "ok",
     "what": "Login no painel (Cloudflare) e sessão salva com token+cookies",
     "run": "main.py sigma-login --save (env SIGMA_USERNAME/SIGMA_PASSWORD)"},
    {"id": "sigma.sync.customers", "site": "sigma", "kind": "sync", "status": "ok",
     "what": "Sincroniza clientes (paginação perPage, cap 100/página)",
     "run": "main.py sigma-sync --what customers --pages 5"},
    {"id": "sigma.sync.expiring", "site": "sigma", "kind": "sync", "status": "ok",
     "what": "Sincroniza clientes a vencer (base p/ alertas)",
     "run": "main.py sigma-sync --what expiring"},
    {"id": "sigma.sync.dashboard", "site": "sigma", "kind": "sync", "status": "ok",
     "what": "Sincroniza 4 charts + métrica recovery do dashboard",
     "run": "main.py sigma-sync --what dashboard"},
    {"id": "sigma.sync.resellers", "site": "sigma", "kind": "sync", "status": "ok",
     "what": "Sincroniza revendedores",
     "run": "main.py sigma-sync --what resellers"},
    {"id": "sigma.sync.statistics", "site": "sigma", "kind": "sync", "status": "ok",
     "what": "Sincroniza estatísticas (minha árvore)",
     "run": "main.py sigma-sync --what statistics"},
    {"id": "sigma.sync.all", "site": "sigma", "kind": "sync", "status": "ok",
     "what": "Sync completo de todos os datasets acima",
     "run": "main.py sigma-sync --what all --pages 5"},
    {"id": "sigma.status", "site": "sigma", "kind": "status", "status": "ok",
     "what": "Validade do token, expiração do painel e contagens do banco local",
     "run": "main.py sigma-status"},
    # ---- sigma: gestão de clientes (CRUD) ------------------------------------
    {"id": "sigma.customer.create", "site": "sigma", "kind": "crud", "status": "ok",
     "what": "Cria cliente (payload mínimo; 422 preenche iterativamente)",
     "run": "main.py sigma-customer-create --username X --package-id P --server-id S"},
    {"id": "sigma.customer.update", "site": "sigma", "kind": "crud", "status": "ok",
     "what": "Edita nota e/ou estende expiração (+dias ou data)",
     "run": "main.py sigma-customer-update ID --note '...' --add-days 30"},
    {"id": "sigma.customer.delete", "site": "sigma", "kind": "crud", "status": "ok",
     "what": "Soft-delete de cliente (restaurável; exige --yes E SIGMA_ALLOW_DESTRUCTIVE=1)",
     "run": "SIGMA_ALLOW_DESTRUCTIVE=1 main.py sigma-customer-delete ID --yes"},
    {"id": "sigma.customer.resync", "site": "sigma", "kind": "crud", "status": "ok",
     "what": "Força resync no painel; retorna a linha COMPLETA do cliente",
     "run": "main.py sigma-customer-resync ID"},
    # ---- sigma: exploradores (desenvolvimento; mantêm o mapa vivo) ------------
    {"id": "sigma.explore.session", "site": "sigma", "kind": "explore", "status": "ok",
     "what": "Sessão fresca + inventário passivo de GETs do dashboard",
     "run": "venv/bin/python core/sigma/explore/01_session.py"},
    {"id": "sigma.explore.map", "site": "sigma", "kind": "explore", "status": "ok",
     "what": "Mapa de rotas/tabelas/screenshot do dashboard (sem cliques)",
     "run": "venv/bin/python core/sigma/explore/02_dashboard_map.py"},
    {"id": "sigma.explore.crawl", "site": "sigma", "kind": "explore", "status": "ok",
     "what": "Crawleo read-only das rotas do mapa (guard + blocklist + --max 5)",
     "run": "venv/bin/python core/sigma/explore/03_route_crawl.py"},
    {"id": "sigma.explore.probe", "site": "sigma", "kind": "explore", "status": "ok",
     "what": "Probe de endpoints GET via fetch no browser",
     "run": "venv/bin/python core/sigma/explore/04_api_probe.py"},
    {"id": "sigma.explore.crudmap", "site": "sigma", "kind": "explore", "status": "ok",
     "what": "BFS nos chunks JS do SPA: mapa de endpoints de mutação",
     "run": "venv/bin/python core/sigma/explore/05_crud_endpoints.py"},
    {"id": "sigma.explore.snapshot", "site": "sigma", "kind": "explore", "status": "ok",
     "what": "Tripwire: snapshot de todos os clientes + diff (rodar antes/depois de escrita)",
     "run": "venv/bin/python core/sigma/explore/06_customers_snapshot.py"},
    {"id": "sigma.explore.lifecycle", "site": "sigma", "kind": "explore", "status": "ok",
     "what": "Ciclo de vida completo de um cliente zz_test_explorer_* (guardião de URL)",
     "run": "venv/bin/python core/sigma/explore/07_test_client_lifecycle.py"},
    {"id": "sigma.servers_packages.sync", "site": "sigma", "kind": "sync", "status": "ok",
     "what": "Catálogo de servers (5) e packages (128) — valida par p/ create",
     "run": "main.py sigma-servers-packages"},
    # ---- sigma: mapeado, ainda sem fiação -------------------------------------
    {"id": "sigma.notices.sync", "site": "sigma", "kind": "sync", "status": "planned",
     "what": "Avisos/notificações do painel",
     "run": "endpoint GET /api/notices/list"},
    {"id": "sigma.customers.top10", "site": "sigma", "kind": "sync", "status": "planned",
     "what": "Top 10 clientes por período (relatórios)",
     "run": "endpoint GET /api/customers/statistics/top10?from_date&to_date"},
    {"id": "sigma.dashboard.ai", "site": "sigma", "kind": "sync", "status": "planned",
     "what": "Análise de IA do dashboard",
     "run": "endpoint GET /api/dashboard/ai-analysis"},
    {"id": "sigma.customers.export", "site": "sigma", "kind": "ops", "status": "planned",
     "what": "Export CSV de todos os clientes (backup)",
     "run": "endpoint GET /api/customers/export"},
    {"id": "sigma.customer.restore", "site": "sigma", "kind": "crud", "status": "planned",
     "what": "Restaura soft-delete",
     "run": "endpoint POST /api/customers/restore (nunca testado)"},
    # ---- sigma: exige aprovação explícita -------------------------------------
    {"id": "sigma.botbot", "site": "sigma", "kind": "messaging", "status": "blocked",
     "what": "BotBot/recovery campaigns — ENVIA mensagens a clientes reais",
     "run": "endpoints mapeados no 05; NÃO usar sem aprovação"},
    {"id": "sigma.bulk", "site": "sigma", "kind": "crud", "status": "blocked",
     "what": "mass-delete / move / migration em lote — destrutivo em massa",
     "run": "endpoints mapeados no 05; NÃO usar sem aprovação"},
    {"id": "sigma.finance", "site": "sigma", "kind": "explore", "status": "blocked",
     "what": "Rotas de financeiro/billing (blocklist do crawl; nunca visitadas)",
     "run": "precisa de explorador read-only dedicado aprovado"},
    # ---- ecommerce_x (placeholder httpbin; padrão para o próximo site) --------
    {"id": "ecommerce.sync", "site": "ecommerce_x", "kind": "sync", "status": "ok",
     "what": "Demo de sincronização de produto (httpbin) + teste de regressão",
     "run": "main.py sync-item ID"},
    # ---- woodcine (painel irmão, 2ª versão do Sigma; CRUD validado por probes 04/10/2026) ----
    {"id": "woodcine.login", "site": "woodcine", "kind": "auth", "status": "ok",
     "what": "Login no painel woodcine: imprime o token (env SIGMA_USERNAME/SIGMA_PASSWORD)",
     "run": "main.py woodcine-login --save"},
    {"id": "woodcine.sync.customers", "site": "woodcine", "kind": "sync", "status": "ok",
     "what": "Sincroniza clientes do woodcine (kinds woodcine.*)",
     "run": "main.py woodcine-sync --what customers --pages 5"},
    {"id": "woodcine.sync.expiring", "site": "woodcine", "kind": "sync", "status": "ok",
     "what": "Clientes a vencer no woodcine",
     "run": "main.py woodcine-sync --what expiring"},
    {"id": "woodcine.sync.dashboard", "site": "woodcine", "kind": "sync", "status": "ok",
     "what": "Charts + métrica recovery do woodcine",
     "run": "main.py woodcine-sync --what dashboard"},
    {"id": "woodcine.sync.resellers", "site": "woodcine", "kind": "sync", "status": "ok",
     "what": "Revendedores do woodcine",
     "run": "main.py woodcine-sync --what resellers"},
    {"id": "woodcine.sync.statistics", "site": "woodcine", "kind": "sync", "status": "ok",
     "what": "Estatísticas de clientes do woodcine",
     "run": "main.py woodcine-sync --what statistics"},
    {"id": "woodcine.sync.servers_packages", "site": "woodcine", "kind": "sync", "status": "ok",
     "what": "Catálogo servers + packages do woodcine",
     "run": "main.py woodcine-servers-packages"},
    {"id": "woodcine.sync.all", "site": "woodcine", "kind": "sync", "status": "ok",
     "what": "Sync completo do woodcine",
     "run": "main.py woodcine-sync --what all --pages 5"},
    {"id": "woodcine.status", "site": "woodcine", "kind": "status", "status": "ok",
     "what": "Token/conta do woodcine + resumo do banco local",
     "run": "main.py woodcine-status"},
    # CRUD validado ao vivo por probes não-mutantes (regra 3): create inválido
    # -> 422 (valida antes, cria nada); delete id inexistente -> 404; tripwire
    # estável (04/10/2026). Créditos LIMITADOS: só executar com pedido do dono.
    {"id": "woodcine.customer.create", "site": "woodcine", "kind": "crud", "status": "ok",
     "what": "Cria cliente (idêntico ao sigma; só com aprovação do dono — créditos limitados)",
     "run": "main.py woodcine-customer-create --username X --package-id P --server-id S"},
    {"id": "woodcine.customer.update", "site": "woodcine", "kind": "crud", "status": "ok",
     "what": "Edita nota e/ou estende expiração (+dias ou data)",
     "run": "main.py woodcine-customer-update ID --note '...' --add-days 30"},
    {"id": "woodcine.customer.delete", "site": "woodcine", "kind": "crud", "status": "ok",
     "what": "Soft-delete de cliente (restaurável; exige --yes E SIGMA_ALLOW_DESTRUCTIVE=1)",
     "run": "SIGMA_ALLOW_DESTRUCTIVE=1 main.py woodcine-customer-delete ID --yes"},
    # ---- newmais (painel irmão família Sigma; créditos LIMITADOS — regra 2 máxima) ----
    {"id": "newmais.login", "site": "newmais", "kind": "auth", "status": "ok",
     "what": "Login no painel newmais: imprime o token (env SIGMA_USERNAME/SIGMA_PASSWORD)",
     "run": "main.py newmais-login --save"},
    {"id": "newmais.sync.customers", "site": "newmais", "kind": "sync", "status": "ok",
     "what": "Sincroniza clientes do newmais (kinds newmais.*)",
     "run": "main.py newmais-sync --what customers --pages 5"},
    {"id": "newmais.sync.expiring", "site": "newmais", "kind": "sync", "status": "ok",
     "what": "Clientes a vencer no newmais",
     "run": "main.py newmais-sync --what expiring"},
    {"id": "newmais.sync.dashboard", "site": "newmais", "kind": "sync", "status": "ok",
     "what": "Charts + métrica recovery do newmais",
     "run": "main.py newmais-sync --what dashboard"},
    {"id": "newmais.sync.resellers", "site": "newmais", "kind": "sync", "status": "ok",
     "what": "Revendedores do newmais",
     "run": "main.py newmais-sync --what resellers"},
    {"id": "newmais.sync.statistics", "site": "newmais", "kind": "sync", "status": "ok",
     "what": "Estatísticas de clientes do newmais",
     "run": "main.py newmais-sync --what statistics"},
    {"id": "newmais.sync.servers_packages", "site": "newmais", "kind": "sync", "status": "ok",
     "what": "Catálogo servers + packages do newmais",
     "run": "main.py newmais-servers-packages"},
    {"id": "newmais.sync.all", "site": "newmais", "kind": "sync", "status": "ok",
     "what": "Sync completo do newmais",
     "run": "main.py newmais-sync --what all --pages 5"},
    {"id": "newmais.status", "site": "newmais", "kind": "status", "status": "ok",
     "what": "Token/conta do newmais + resumo do banco local",
     "run": "main.py newmais-status"},
    # CRUD validado ao vivo por probes não-mutantes (regra 3): create inválido
    # -> 422; delete id inexistente -> 404; tripwire estável (04/10/2026).
    # Créditos LIMITADOS: só executar com pedido do dono.
    {"id": "newmais.customer.create", "site": "newmais", "kind": "crud", "status": "ok",
     "what": "Cria cliente (idêntico ao sigma; só com aprovação do dono — créditos limitados)",
     "run": "main.py newmais-customer-create --username X --package-id P --server-id S"},
    {"id": "newmais.customer.update", "site": "newmais", "kind": "crud", "status": "ok",
     "what": "Edita nota e/ou estende expiração (+dias ou data)",
     "run": "main.py newmais-customer-update ID --note '...' --add-days 30"},
    {"id": "newmais.customer.delete", "site": "newmais", "kind": "crud", "status": "ok",
     "what": "Soft-delete de cliente (restaurável; exige --yes E SIGMA_ALLOW_DESTRUCTIVE=1)",
     "run": "SIGMA_ALLOW_DESTRUCTIVE=1 main.py newmais-customer-delete ID --yes"},
    # ---- blackbr (família Sigma; painel de revendas com créditos ILIMITADOS) ----
    {"id": "blackbr.login", "site": "blackbr", "kind": "auth", "status": "ok",
     "what": "Login no blackbr: imprime o token (env SIGMA_USERNAME/SIGMA_PASSWORD)",
     "run": "main.py blackbr-login --save"},
    {"id": "blackbr.sync.customers", "site": "blackbr", "kind": "sync", "status": "ok",
     "what": "Sincroniza clientes do blackbr (kinds blackbr.*)",
     "run": "main.py blackbr-sync --what customers --pages 5"},
    {"id": "blackbr.sync.expiring", "site": "blackbr", "kind": "sync", "status": "ok",
     "what": "Clientes a vencer no blackbr",
     "run": "main.py blackbr-sync --what expiring"},
    {"id": "blackbr.sync.dashboard", "site": "blackbr", "kind": "sync", "status": "ok",
     "what": "Charts + métrica recovery do blackbr",
     "run": "main.py blackbr-sync --what dashboard"},
    {"id": "blackbr.sync.resellers", "site": "blackbr", "kind": "sync", "status": "ok",
     "what": "Revendedores do blackbr",
     "run": "main.py blackbr-sync --what resellers"},
    {"id": "blackbr.sync.statistics", "site": "blackbr", "kind": "sync", "status": "ok",
     "what": "Estatísticas de clientes do blackbr",
     "run": "main.py blackbr-sync --what statistics"},
    {"id": "blackbr.sync.servers_packages", "site": "blackbr", "kind": "sync", "status": "ok",
     "what": "Catálogo servers + packages do blackbr",
     "run": "main.py blackbr-servers-packages"},
    {"id": "blackbr.sync.all", "site": "blackbr", "kind": "sync", "status": "ok",
     "what": "Sync completo do blackbr",
     "run": "main.py blackbr-sync --what all --pages 5"},
    {"id": "blackbr.status", "site": "blackbr", "kind": "status", "status": "ok",
     "what": "Token/conta do blackbr + resumo do banco local",
     "run": "main.py blackbr-status"},
    # CRUD validado ao vivo: ciclo real completo (criar/renovar/senha/playlist/
    # deletar verificado) no karpathy noturno 04/10/2026.
    {"id": "blackbr.customer.create", "site": "blackbr", "kind": "crud", "status": "ok",
     "what": "Cria cliente (payload mínimo; 422 preenche iterativamente)",
     "run": "main.py blackbr-customer-create --username X --package-id P --server-id S"},
    {"id": "blackbr.customer.update", "site": "blackbr", "kind": "crud", "status": "ok",
     "what": "Edita cliente (strip de username/password no update — UPDATE_STRIP_FIELDS)",
     "run": "main.py blackbr-customer-update ID --note '...' --add-days 30"},
    {"id": "blackbr.customer.delete", "site": "blackbr", "kind": "crud", "status": "ok",
     "what": "Soft-delete de cliente (restaurável; exige --yes E SIGMA_ALLOW_DESTRUCTIVE=1)",
     "run": "SIGMA_ALLOW_DESTRUCTIVE=1 main.py blackbr-customer-delete ID --yes"},

    # ---- rocketgestor (Django server-rendered NÃO-sigma; gerenciador multipainel com créditos INEXISTENTES — zz_test_* LIVRES, clientes reais intocados) ----
    {"id": "rocketgestor.login", "site": "rocketgestor", "kind": "auth", "status": "ok",
     "what": "Login no Rocket Gestor (contas em rocketgestor_accounts.json)",
     "run": "main.py rocketgestor-login --save"},
    {"id": "rocketgestor.status", "site": "rocketgestor", "kind": "status", "status": "ok",
     "what": "Conta ativa + sessão + espelho local do Rocket Gestor",
     "run": "main.py rocketgestor-status"},
    {"id": "rocketgestor.sync", "site": "rocketgestor", "kind": "sync", "status": "ok",
     "what": "Espelha clientes do Rocket Gestor (kinds rocketgestor.*)",
     "run": "main.py rocketgestor-sync"},
    {"id": "rocketgestor.listar", "site": "rocketgestor", "kind": "list", "status": "ok",
     "what": "Lista clientes ao vivo do Rocket Gestor (com login IPTV)",
     "run": "main.py rocketgestor-listar"},
    {"id": "rocketgestor.buscar", "site": "rocketgestor", "kind": "search", "status": "ok",
     "what": "Busca cliente por nome/login/telefone/id",
     "run": "main.py rocketgestor-buscar TERMO"},
    {"id": "rocketgestor.customer.create", "site": "rocketgestor", "kind": "crud", "status": "ok",
     "what": "Cria cliente no Rocket Gestor (zz_test_* livres; reais só c/ aprovação)",
     "run": "main.py rocketgestor-criar --nome X --usuario X --vencimento 31/12/2026"},
    {"id": "rocketgestor.customer.update", "site": "rocketgestor", "kind": "crud", "status": "ok",
     "what": "Edita vencimento/valor/plano/forma/telas (forma obrigatória pelo painel)",
     "run": "main.py rocketgestor-editar ID --vencimento 2027-01-15 --forma Pix"},
    {"id": "rocketgestor.customer.delete", "site": "rocketgestor", "kind": "crud", "status": "ok",
     "what": "Soft delete → lixeira (restaurável); zz_test_* livres",
     "run": "SIGMA_ALLOW_DESTRUCTIVE=1 main.py rocketgestor-apagar ID --yes"},
]
